### ISSUE TITLE
Docker build failing on linting errors.

### ISSUE THREAD

**Issue by HelinJG** [osisoft/sample-adh-grafana-nodejs#30]
### Command run
`docker build -t grafana-adh .`
### Log output
> > [appbuild 6/6] RUN npm run build:                                                                                                          
#13 0.692 
#13 0.692 > sds-grafana-sample@1.4.1 build
#13 0.692 > grafana-toolkit plugin:build
#13 0.692 
#13 1.879   Using Node.js v15.14.0
#13 2.867   Using @grafana/toolkit v8.5.2
#13 2.869 - Preparing
#13 2.872 ✔ Preparing
#13 2.873 - Linting
#13 5.272   
#13 5.272   
#13 5.276   
#13 5.276   /usr/src/app/src/DataSource.spec.ts
#13 5.276     358:1  error  Delete `⏎`  prettier/prettier
#13 5.276   
#13 5.276   /usr/src/app/src/DataSource.ts
#13 5.276     108:1   error  Delete `············`           prettier/prettier
#13 5.276     109:28  error  Insert `;`                      prettier/prettier
#13 5.276     112:62  error  Replace `"true"` with `'true'`  prettier/prettier
#13 5.276     114:14  error  Delete `⏎···········`           prettier/prettier
#13 5.276   
#13 5.276   /usr/src/app/src/debounce.ts
#13 5.276     20:3   error  React Hook "useEffect" is called in function "debounce" that is neither a React function component nor a custom React Hook function. React component names must start with an uppercase letter. React Hook names must start with the word "use"  react-hooks/rules-of-hooks
#13 5.276     20:37  error  React Hook useEffect has a missing dependency: 'teardown'. Either include it or remove the dependency array                                                                                                                                      react-hooks/exhaustive-deps
#13 5.276   
#13 5.276   ✖ 7 problems (7 errors, 0 warnings)
#13 5.276     5 errors and 0 warnings potentially fixable with the `--fix` option.
#13 5.276   
#13 5.276   
#13 5.276   
#13 5.276 ✖ 7 linting errors found in 7 files
#13 5.278   Trace: Error: 7 linting errors found in 7 files
#13 5.278       at /usr/src/app/node_modules/@grafana/toolkit/src/cli/tasks/plugin.build.js:95:15
#13 5.278       at Generator.next (<anonymous>)
#13 5.278       at fulfilled (/usr/src/app/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:114:62)
#13 5.278       at processTicksAndRejections (node:internal/process/task_queues:94:5)
#13 5.278       at /usr/src/app/node_modules/@grafana/toolkit/src/cli/utils/useSpinner.js:20:21
#13 5.278       at Generator.throw (<anonymous>)
#13 5.278       at rejected (/usr/src/app/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:115:69)
#13 5.278       at processTicksAndRejections (node:internal/process/task_queues:94:5)
------
executor failed running [/bin/sh -c npm run build]: exit code: 1

**Comment by cbardini** [comment]
Sample updated to resolve linting and React hook rule violations.
